-- ============================================================================
-- 0001_rls.sql — Row Level Security policies + helper function + auth trigger
--
-- This file is intentionally NOT generated by drizzle-kit and MUST be applied
-- AFTER 0000_init.sql. See docs/02-DATABASE.md §5 for the security spec.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Helper: current user's role, looked up from public.profiles.
-- SECURITY DEFINER so it bypasses RLS on profiles (otherwise infinite recursion).
-- ---------------------------------------------------------------------------
create or replace function public.user_role()
returns public.user_role
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

grant execute on function public.user_role() to authenticated;

-- ---------------------------------------------------------------------------
-- Trigger: create a profile row whenever a new auth user is created.
-- The new user's first_name / last_name / role come from raw_user_meta_data
-- (set by the admin invite flow or signup).
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, first_name, last_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'first_name', ''),
    coalesce(new.raw_user_meta_data->>'last_name', ''),
    coalesce((new.raw_user_meta_data->>'role')::public.user_role, 'student')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- Enable RLS on every table.
-- ---------------------------------------------------------------------------
alter table public.profiles                enable row level security;
alter table public.academic_years          enable row level security;
alter table public.classes                 enable row level security;
alter table public.subjects                enable row level security;
alter table public.class_subjects          enable row level security;
alter table public.teacher_assignments     enable row level security;
alter table public.student_enrollments     enable row level security;
alter table public.student_subject_access  enable row level security;
alter table public.chapters                enable row level security;
alter table public.sequences               enable row level security;
alter table public.resources               enable row level security;
alter table public.quizzes                 enable row level security;
alter table public.questions               enable row level security;
alter table public.question_options        enable row level security;
alter table public.quiz_attempts           enable row level security;
alter table public.quiz_answers            enable row level security;
alter table public.progress                enable row level security;
alter table public.notifications           enable row level security;
alter table public.activity_logs           enable row level security;

-- ===========================================================================
-- profiles
-- - admin: all
-- - every user can read their own profile
-- ===========================================================================
create policy "profiles_select_own_or_admin" on public.profiles
  for select to authenticated
  using (id = auth.uid() or public.user_role() = 'admin');

create policy "profiles_admin_all" on public.profiles
  for all to authenticated
  using (public.user_role() = 'admin')
  with check (public.user_role() = 'admin');

create policy "profiles_self_update" on public.profiles
  for update to authenticated
  using (id = auth.uid())
  with check (id = auth.uid() and role = (select role from public.profiles where id = auth.uid()));

-- ===========================================================================
-- academic_years — admin/manager write, everyone reads.
-- ===========================================================================
create policy "academic_years_select_all" on public.academic_years
  for select to authenticated using (true);

create policy "academic_years_admin_manager_all" on public.academic_years
  for all to authenticated
  using (public.user_role() in ('admin', 'manager'))
  with check (public.user_role() in ('admin', 'manager'));

-- ===========================================================================
-- subjects — admin/manager write; teachers/students read.
-- ===========================================================================
create policy "subjects_select_all" on public.subjects
  for select to authenticated using (true);

create policy "subjects_admin_manager_all" on public.subjects
  for all to authenticated
  using (public.user_role() in ('admin', 'manager'))
  with check (public.user_role() in ('admin', 'manager'));

-- ===========================================================================
-- classes
-- - admin/manager: full access
-- - teacher: read classes where assigned
-- - student: read class where enrolled
-- ===========================================================================
create policy "classes_admin_manager_all" on public.classes
  for all to authenticated
  using (public.user_role() in ('admin', 'manager'))
  with check (public.user_role() in ('admin', 'manager'));

create policy "classes_teacher_select" on public.classes
  for select to authenticated
  using (
    public.user_role() = 'teacher'
    and exists (
      select 1 from public.teacher_assignments ta
      where ta.teacher_id = auth.uid() and ta.class_id = classes.id
    )
  );

create policy "classes_student_select" on public.classes
  for select to authenticated
  using (
    public.user_role() = 'student'
    and exists (
      select 1 from public.student_enrollments se
      where se.student_id = auth.uid() and se.class_id = classes.id
    )
  );

-- ===========================================================================
-- class_subjects
-- ===========================================================================
create policy "class_subjects_admin_manager_all" on public.class_subjects
  for all to authenticated
  using (public.user_role() in ('admin', 'manager'))
  with check (public.user_role() in ('admin', 'manager'));

create policy "class_subjects_teacher_select" on public.class_subjects
  for select to authenticated
  using (
    public.user_role() = 'teacher'
    and exists (
      select 1 from public.teacher_assignments ta
      where ta.teacher_id = auth.uid()
        and ta.class_id = class_subjects.class_id
        and ta.subject_id = class_subjects.subject_id
    )
  );

create policy "class_subjects_student_select" on public.class_subjects
  for select to authenticated
  using (
    public.user_role() = 'student'
    and exists (
      select 1 from public.student_subject_access ssa
      where ssa.student_id = auth.uid()
        and ssa.class_id = class_subjects.class_id
        and ssa.subject_id = class_subjects.subject_id
    )
  );

-- ===========================================================================
-- teacher_assignments — admin/manager write; teacher reads own.
-- ===========================================================================
create policy "teacher_assignments_admin_manager_all" on public.teacher_assignments
  for all to authenticated
  using (public.user_role() in ('admin', 'manager'))
  with check (public.user_role() in ('admin', 'manager'));

create policy "teacher_assignments_teacher_select_own" on public.teacher_assignments
  for select to authenticated
  using (teacher_id = auth.uid());

-- ===========================================================================
-- student_enrollments — admin/manager write; student reads own.
-- ===========================================================================
create policy "student_enrollments_admin_manager_all" on public.student_enrollments
  for all to authenticated
  using (public.user_role() in ('admin', 'manager'))
  with check (public.user_role() in ('admin', 'manager'));

create policy "student_enrollments_student_select_own" on public.student_enrollments
  for select to authenticated
  using (student_id = auth.uid());

create policy "student_enrollments_teacher_select_scope" on public.student_enrollments
  for select to authenticated
  using (
    public.user_role() = 'teacher'
    and exists (
      select 1 from public.teacher_assignments ta
      where ta.teacher_id = auth.uid() and ta.class_id = student_enrollments.class_id
    )
  );

-- ===========================================================================
-- student_subject_access — admin/manager write; student reads own.
-- ===========================================================================
create policy "student_subject_access_admin_manager_all" on public.student_subject_access
  for all to authenticated
  using (public.user_role() in ('admin', 'manager'))
  with check (public.user_role() in ('admin', 'manager'));

create policy "student_subject_access_student_select_own" on public.student_subject_access
  for select to authenticated
  using (student_id = auth.uid());

create policy "student_subject_access_teacher_select_scope" on public.student_subject_access
  for select to authenticated
  using (
    public.user_role() = 'teacher'
    and exists (
      select 1 from public.teacher_assignments ta
      where ta.teacher_id = auth.uid()
        and ta.class_id = student_subject_access.class_id
        and ta.subject_id = student_subject_access.subject_id
    )
  );

-- ===========================================================================
-- chapters
-- - admin/manager: all
-- - teacher: full within (class+subject) assigned
-- - student: read if has student_subject_access (any status)
-- ===========================================================================
create policy "chapters_admin_manager_all" on public.chapters
  for all to authenticated
  using (public.user_role() in ('admin', 'manager'))
  with check (public.user_role() in ('admin', 'manager'));

create policy "chapters_teacher_scope_all" on public.chapters
  for all to authenticated
  using (
    public.user_role() = 'teacher'
    and exists (
      select 1 from public.teacher_assignments ta
      where ta.teacher_id = auth.uid()
        and ta.class_id = chapters.class_id
        and ta.subject_id = chapters.subject_id
    )
  )
  with check (
    public.user_role() = 'teacher'
    and exists (
      select 1 from public.teacher_assignments ta
      where ta.teacher_id = auth.uid()
        and ta.class_id = chapters.class_id
        and ta.subject_id = chapters.subject_id
    )
  );

create policy "chapters_student_select" on public.chapters
  for select to authenticated
  using (
    public.user_role() = 'student'
    and exists (
      select 1 from public.student_subject_access ssa
      where ssa.student_id = auth.uid()
        and ssa.class_id = chapters.class_id
        and ssa.subject_id = chapters.subject_id
    )
  );

-- ===========================================================================
-- sequences — same scope as parent chapter.
-- ===========================================================================
create policy "sequences_admin_manager_all" on public.sequences
  for all to authenticated
  using (public.user_role() in ('admin', 'manager'))
  with check (public.user_role() in ('admin', 'manager'));

create policy "sequences_teacher_scope_all" on public.sequences
  for all to authenticated
  using (
    public.user_role() = 'teacher'
    and exists (
      select 1
      from public.chapters c
      join public.teacher_assignments ta
        on ta.class_id = c.class_id and ta.subject_id = c.subject_id
      where c.id = sequences.chapter_id and ta.teacher_id = auth.uid()
    )
  )
  with check (
    public.user_role() = 'teacher'
    and exists (
      select 1
      from public.chapters c
      join public.teacher_assignments ta
        on ta.class_id = c.class_id and ta.subject_id = c.subject_id
      where c.id = sequences.chapter_id and ta.teacher_id = auth.uid()
    )
  );

create policy "sequences_student_select" on public.sequences
  for select to authenticated
  using (
    public.user_role() = 'student'
    and exists (
      select 1
      from public.chapters c
      join public.student_subject_access ssa
        on ssa.class_id = c.class_id and ssa.subject_id = c.subject_id
      where c.id = sequences.chapter_id and ssa.student_id = auth.uid()
    )
  );

-- ===========================================================================
-- resources
-- - student: read only if published AND access granted AND in publish window
-- ===========================================================================
create policy "resources_admin_manager_all" on public.resources
  for all to authenticated
  using (public.user_role() in ('admin', 'manager'))
  with check (public.user_role() in ('admin', 'manager'));

create policy "resources_teacher_scope_all" on public.resources
  for all to authenticated
  using (
    public.user_role() = 'teacher'
    and exists (
      select 1
      from public.chapters c
      join public.teacher_assignments ta
        on ta.class_id = c.class_id and ta.subject_id = c.subject_id
      where c.id = resources.chapter_id and ta.teacher_id = auth.uid()
    )
  )
  with check (
    public.user_role() = 'teacher'
    and exists (
      select 1
      from public.chapters c
      join public.teacher_assignments ta
        on ta.class_id = c.class_id and ta.subject_id = c.subject_id
      where c.id = resources.chapter_id and ta.teacher_id = auth.uid()
    )
  );

create policy "resources_student_select_published" on public.resources
  for select to authenticated
  using (
    public.user_role() = 'student'
    and status = 'published'
    and published_at is not null
    and published_at <= now()
    and (unpublish_at is null or unpublish_at > now())
    and exists (
      select 1
      from public.chapters c
      join public.student_subject_access ssa
        on ssa.class_id = c.class_id and ssa.subject_id = c.subject_id
      where c.id = resources.chapter_id and ssa.student_id = auth.uid()
    )
  );

-- ===========================================================================
-- quizzes — same pattern; student only sees published quizzes inside window.
-- ===========================================================================
create policy "quizzes_admin_manager_all" on public.quizzes
  for all to authenticated
  using (public.user_role() in ('admin', 'manager'))
  with check (public.user_role() in ('admin', 'manager'));

create policy "quizzes_teacher_scope_all" on public.quizzes
  for all to authenticated
  using (
    public.user_role() = 'teacher'
    and exists (
      select 1 from public.teacher_assignments ta
      where ta.teacher_id = auth.uid()
        and ta.class_id = quizzes.class_id
        and ta.subject_id = quizzes.subject_id
    )
  )
  with check (
    public.user_role() = 'teacher'
    and exists (
      select 1 from public.teacher_assignments ta
      where ta.teacher_id = auth.uid()
        and ta.class_id = quizzes.class_id
        and ta.subject_id = quizzes.subject_id
    )
  );

create policy "quizzes_student_select_published" on public.quizzes
  for select to authenticated
  using (
    public.user_role() = 'student'
    and status = 'published'
    and (opens_at is null or opens_at <= now())
    and (closes_at is null or closes_at > now())
    and exists (
      select 1 from public.student_subject_access ssa
      where ssa.student_id = auth.uid()
        and ssa.class_id = quizzes.class_id
        and ssa.subject_id = quizzes.subject_id
    )
  );

-- ===========================================================================
-- questions — readable when parent quiz is readable.
-- ===========================================================================
create policy "questions_admin_manager_all" on public.questions
  for all to authenticated
  using (public.user_role() in ('admin', 'manager'))
  with check (public.user_role() in ('admin', 'manager'));

create policy "questions_teacher_scope_all" on public.questions
  for all to authenticated
  using (
    public.user_role() = 'teacher'
    and exists (
      select 1
      from public.quizzes q
      join public.teacher_assignments ta
        on ta.class_id = q.class_id and ta.subject_id = q.subject_id
      where q.id = questions.quiz_id and ta.teacher_id = auth.uid()
    )
  )
  with check (
    public.user_role() = 'teacher'
    and exists (
      select 1
      from public.quizzes q
      join public.teacher_assignments ta
        on ta.class_id = q.class_id and ta.subject_id = q.subject_id
      where q.id = questions.quiz_id and ta.teacher_id = auth.uid()
    )
  );

create policy "questions_student_select" on public.questions
  for select to authenticated
  using (
    public.user_role() = 'student'
    and exists (
      select 1 from public.quizzes q
      where q.id = questions.quiz_id
        and q.status = 'published'
        and (q.opens_at is null or q.opens_at <= now())
        and (q.closes_at is null or q.closes_at > now())
        and exists (
          select 1 from public.student_subject_access ssa
          where ssa.student_id = auth.uid()
            and ssa.class_id = q.class_id
            and ssa.subject_id = q.subject_id
        )
    )
  );

-- ===========================================================================
-- question_options
-- IMPORTANT: students MUST NOT receive is_correct before they submit.
-- The student-facing read goes through the service role / Server Actions
-- which strip is_correct. No "for select" policy granted to students here.
-- ===========================================================================
create policy "question_options_admin_manager_all" on public.question_options
  for all to authenticated
  using (public.user_role() in ('admin', 'manager'))
  with check (public.user_role() in ('admin', 'manager'));

create policy "question_options_teacher_scope_all" on public.question_options
  for all to authenticated
  using (
    public.user_role() = 'teacher'
    and exists (
      select 1
      from public.questions qu
      join public.quizzes q on q.id = qu.quiz_id
      join public.teacher_assignments ta
        on ta.class_id = q.class_id and ta.subject_id = q.subject_id
      where qu.id = question_options.question_id and ta.teacher_id = auth.uid()
    )
  )
  with check (
    public.user_role() = 'teacher'
    and exists (
      select 1
      from public.questions qu
      join public.quizzes q on q.id = qu.quiz_id
      join public.teacher_assignments ta
        on ta.class_id = q.class_id and ta.subject_id = q.subject_id
      where qu.id = question_options.question_id and ta.teacher_id = auth.uid()
    )
  );

-- ===========================================================================
-- quiz_attempts — students own theirs; teachers/admins/managers read in scope.
-- ===========================================================================
create policy "quiz_attempts_admin_manager_all" on public.quiz_attempts
  for all to authenticated
  using (public.user_role() in ('admin', 'manager'))
  with check (public.user_role() in ('admin', 'manager'));

create policy "quiz_attempts_student_own_all" on public.quiz_attempts
  for all to authenticated
  using (student_id = auth.uid())
  with check (student_id = auth.uid());

create policy "quiz_attempts_teacher_scope_select" on public.quiz_attempts
  for select to authenticated
  using (
    public.user_role() = 'teacher'
    and exists (
      select 1
      from public.quizzes q
      join public.teacher_assignments ta
        on ta.class_id = q.class_id and ta.subject_id = q.subject_id
      where q.id = quiz_attempts.quiz_id and ta.teacher_id = auth.uid()
    )
  );

-- ===========================================================================
-- quiz_answers — same shape as quiz_attempts.
-- ===========================================================================
create policy "quiz_answers_admin_manager_all" on public.quiz_answers
  for all to authenticated
  using (public.user_role() in ('admin', 'manager'))
  with check (public.user_role() in ('admin', 'manager'));

create policy "quiz_answers_student_own_all" on public.quiz_answers
  for all to authenticated
  using (
    exists (
      select 1 from public.quiz_attempts qa
      where qa.id = quiz_answers.attempt_id and qa.student_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.quiz_attempts qa
      where qa.id = quiz_answers.attempt_id and qa.student_id = auth.uid()
    )
  );

create policy "quiz_answers_teacher_scope_select" on public.quiz_answers
  for select to authenticated
  using (
    public.user_role() = 'teacher'
    and exists (
      select 1
      from public.quiz_attempts qa
      join public.quizzes q on q.id = qa.quiz_id
      join public.teacher_assignments ta
        on ta.class_id = q.class_id and ta.subject_id = q.subject_id
      where qa.id = quiz_answers.attempt_id and ta.teacher_id = auth.uid()
    )
  );

-- ===========================================================================
-- progress — student writes/reads own; teacher/manager/admin read in scope.
-- ===========================================================================
create policy "progress_admin_manager_all" on public.progress
  for all to authenticated
  using (public.user_role() in ('admin', 'manager'))
  with check (public.user_role() in ('admin', 'manager'));

create policy "progress_student_own_all" on public.progress
  for all to authenticated
  using (student_id = auth.uid())
  with check (student_id = auth.uid());

create policy "progress_teacher_scope_select" on public.progress
  for select to authenticated
  using (
    public.user_role() = 'teacher'
    and exists (
      select 1
      from public.resources r
      join public.chapters c on c.id = r.chapter_id
      join public.teacher_assignments ta
        on ta.class_id = c.class_id and ta.subject_id = c.subject_id
      where r.id = progress.resource_id and ta.teacher_id = auth.uid()
    )
  );

-- ===========================================================================
-- notifications — every user owns theirs.
-- ===========================================================================
create policy "notifications_self_all" on public.notifications
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "notifications_admin_all" on public.notifications
  for all to authenticated
  using (public.user_role() = 'admin')
  with check (public.user_role() = 'admin');

-- ===========================================================================
-- activity_logs — admin reads everything; users read their own.
-- Writes happen server-side via service role only.
-- ===========================================================================
create policy "activity_logs_self_select" on public.activity_logs
  for select to authenticated
  using (user_id = auth.uid());

create policy "activity_logs_admin_select" on public.activity_logs
  for select to authenticated
  using (public.user_role() = 'admin');
